### ISSUE TITLE
seek a podcast mp3 then lost duration

### ISSUE THREAD

**Issue by newbdez33** [dimitris-c/AudioStreaming#5] opened 2020-11-30 04:43 UTC
This podcast:

> https://pdst.fm/e/chtbl.com/track/95538/traffic.megaphone.fm/ADL7076246752.mp3

Playing it is fine, but when you do "seek", the player lost duration(duration == 0).
And it can not perform seek anymore( will cause crash ).

There are also other podcast have same issue.
I'm looking into the issue, but unless you've already addressed it :)

**Comment by dimitris-c** [comment] 2020-11-30 10:48
Hey

Since I can't reproduce this could you please let me know more of the environment.
I'll need to setup an issue template to have more context of the issues raised.

**Comment by newbdez33** [comment] 2020-12-01 04:38
I'm using Xcode 12.2, iOS 14.2

With latest master branch of project Example.
It's not all podcast can reproduce this.
please try this mp3:
> https://pdst.fm/e/chtbl.com/track/95538/traffic.megaphone.fm/ADL7076246752.mp3

**Comment by dimitris-c** [comment] 2020-12-01 10:56
I reproduced this issue. 
This seems to be with the header fields of the response and I'm handling it, I didn't take into account the case insensitive that sometimes servers send back.

This is fixed by #7

**Closed by dimitris-c** 2020-12-01 10:56 UTC
